export const sushiMenu = [
    {
        category: 'Sushi',
        subcategory: 'nigiri',
        subdescription: 'wybrane przez sushi chefa',
        setType: 'Omakase Nigiri',
        meal: [
            {
                name: '4 szt.',
                price: '38',
                description: '',
                isVege: false,
            },
            {
                name: '6 szt.',
                price: '52',
                description: '',
                isVege: false,
            },
            {
                name: '12 szt.',
                price: '89',
                description: '',
                isVege: false,
            },
            {
                name: '16 szt.',
                price: '119',
                description: '',
                isVege: false,
            },
        ],
    },
    {
        category: 'Sushi',
        setType: 'sashimi',
        subcategory: 'sashimi',
        subdescription: '',
        meal: [
            {
                name: '4 szt.',
                price: '30',
                description: '',
                isVege: false,
            },
            {
                name: '6 szt.',
                price: '42',
                description: '',
                isVege: false,
            },
            {
                name: '12 szt.',
                price: '52',
                description: '',
                isVege: false,
            },
            {
                name: '16 szt.',
                price: '70',
                description: '',
                isVege: false,
            },
        ],
    },
    {
        category: 'Sushi',
        setType: 'chirashi',
        subcategory: 'chirashi',
        subdescription: '',
        meal: [
            {
                name: 'chirashi sushi',
                price: '85',
                description: '',
                isVege: false,
            },
        ],
    },
    {
        category: 'Sushi',
        setType: 'futomaki',
        subcategory: 'futomaki',
        subdescription: '',
        meal: [
            {
                name: 'tatar maki',
                description: 'tatar z tunczyka lub łososia',
                price: '44',
                isVege: false,
            },
            {
                name: 'tatar maki',
                description: 'tatar z tunczyka lub łososia',
                price: '44',
                isVege: false,
            },
            {
                name: 'tatar maki',
                description: 'tatar z tunczyka lub łososia',
                price: '44',
                isVege: false,
            },
            {
                name: 'tatar maki',
                description: 'tatar z tunczyka lub łososia',
                price: '44',
                isVege: false,
            },
            {
                name: 'tatar maki',
                description: 'tatar z tunczyka lub łososia',
                isVege: true,
                price: '44',
            },
        ],
    },
    {
        category: 'Sushi',
        setType: 'uramaki',
        subcategory: 'uramaki',
        subdescription: '',
        meal: [
            {
                name: 'philadelphia roll',
                description: 'łosos',
                price: '44',
                isVege: false,
            },
            {
                name: 'philadelphia roll',
                description: 'łosos, serek Philadelphia',
                price: '44',
                isVege: false,
            },
            {
                name: 'philadelphia roll',
                description: 'łosos, serek Philadelphia',
                price: '44',
                isVege: false,
            },
            {
                name: 'philadelphia roll',
                description: 'łosos, serek Philadelphia',
                price: '44',
                isVege: false,
            },
            {
                name: 'tatar maki',
                description: 'tatar z tunczyka lub łososia',
                isVege: true,
                price: '44',
            },
        ],
    },
    {
        category: 'Sushi',
        subcategory: 'Zestawy Sushi',
        setType: 'Maki Set',
        subdescription: '',
        meal: [
            {
                name: 'Vegan Set',
                description: '3 x 8 szt. maki vegan',
                isVege: true,
                price: '98',
            },
            {
                name: 'Mały',
                description: '3 x 8 szt. maki vegan',
                price: '44',
                isVege: false,
            },
            {
                name: 'Mały',
                description: '3 x 8 szt. maki vegan',
                price: '44',
                isVege: false,
            },
            {
                name: 'Mały',
                description: '3 x 8 szt. maki vegan',
                price: '44',
                isVege: false,
            },
            {
                name: 'Mały',
                description: '3 x 8 szt. maki vegan',
                price: '44',
                isVege: false,
            },
        ],
    },
    {
        category: 'Sushi',
        subcategory: 'Zestawy Sushi',
        setType: 'Sushi Sets',
        subdescription: '',
        meal: [
            {
                name: 'Vegan Set',
                description: '3 x 8 szt. maki vegan',
                isVege: true,
                price: '98',
            },
            {
                name: 'Mały',
                description: '3 x 8 szt. maki vegan',
                price: '44',
                isVege: true,
            },
            {
                name: 'Mały',
                description: '3 x 8 szt. maki vegan',
                price: '44',
                isVege: true,
            },
            {
                name: 'Mały',
                description: '3 x 8 szt. maki vegan',
                price: '44',
                isVege: true,
            },
            {
                name: 'Mały',
                description: '3 x 8 szt. maki vegan',
                price: '44',
                isVege: true,
            },
        ],
    },
    {
        category: 'przystawki',
        subcategory: '',
        setType: '',
        subdescription: '',
        meal: [
            {
                name: 'Edamame',
                description: 'z solą lub koreanskim chili',
                price: '17',
                isVege: true,
            },
            {
                description: 'z glazurą sojową',
                price: '54',
                isVege: false,
                name: 'Osmiornica',
            },
            {
                name: 'Krewetki',
                description: 'w panko',
                price: '45',
                isVege: false,
            },
            {
                name: 'Kukurydza',
                description: 'w tempurze',
                price: '25',
                isVege: false,
            },
            {
                name: 'Biała ryba',
                description: 'gazpacho z yuzu i awokado',
                price: '42',
                isVege: false,
            },
            {
                name: 'Spring rolls',
                description: 'z krewetkami i grillowanym ananasem',
                price: '32',
                isVege: false,
            },
        ],
    },
    {
        category: 'zupy',
        subcategory: '',
        setType: '',
        meal: [
            {
                name: 'Miso',
                description: '',
                isVege: false,
                price: '12',
            },
            {
                name: 'Ramen',
                description: 'z wołowiną (mały / duży)',
                isVege: false,
                price: '18/32',
            },
            {
                name: 'Ramen',
                description: 'z owocami morza (mały / duży)',
                isVege: false,
                price: '20/36',
            },
            {
                name: 'Curry udon',
                description: 'z krewetkami i jajkiem',
                isVege: false,
                price: '29',
            },
        ],
        subdescription: '',
    },
    {
        category: 'Dania Główne',
        subcategory: '',
        setType: '',
        subdescription: '',
        meal: [
            {
                name: 'Makaron z kaczką konfitowaną',
                description: '',
                isVege: false,
                price: '45',
            },
            {
                name: 'Kaczka z pieca opalanego drzewem',
                description: 'z sezonowymi japonskimi grzybami',
                isVege: false,
                price: '48',
            },
            {
                name: 'Makaron udon',
                description: 'z marywowaną wołowiną',
                isVege: false,
                price: '40',
            },
            {
                name: 'Pieczone żebro wołowe',
                description: 'w sosie pieprzowym z btatami i wodorostami',
                isVege: false,
                price: '56',
            },
        ],
    },
    {
        category: 'Desery',
        subcategory: '',
        setType: '',
        subdescription: '',
        meal: [
            {
                name: 'Torcik',
                description: 'z zielonej herbaty z panią yuzu',
                price: '25',
                isVege: true,
            },
            {
                name: 'Torcik',
                description: 'z zielonej herbaty z panią yuzu',
                price: '25',
                isVege: true,
            },
            {
                name: 'Torcik',
                description: 'z zielonej herbaty z panią yuzu',
                price: '25',
                isVege: true,
            },
        ],
    },
]
